@startuml

'Diagramme de classes (PlantUML)'

'Configuration charte graphique'
hide empty methods
hide circle
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}

'Classes, énumérations, etc.'
class MiniSocs {
  -NetworkId: Interger
  -Nom: String
  -Descrip: String
  -IsOpen: Bool
  -MembersList()
  -ModérateurList()
  -MessageList()
}


class Utilisateur {
  - IdUtilisateur: Integer
  - nom: String
  - prénom: String
  - AdresseMail: String
  -EtatCompte: ÉtatCompte
  -Pseudonyme: String
  -ActiverCompte()
  -DesactiverCompte()
  -ConfigurerCompte()
  -Créer()
  -Joindre()
}


class Membre{
  -IdMembre:Integer
  -Nom:String
  -Prenom:String
  -AdresseMail:String
  - Pseudonyme:String
  -PosterMessage()
  -CacherMessage()
  -DesactiverCompte()
  -ConfiguerCompte()
}


class Administrateur{
  -IdAdmin:Integer
  -Nom:String
  -Prenom:String
  -AdressMail:String
  -listerUtilisateur()
  -bloquerUtilisateur()
  -débloquerUtilisateur()
  -RetirerUtilisateur()
  -AjouterUtilisateur()
  -AjouterMembre()
  -PromouvoirMembre()
}
class Modérateur {
  -IdModérateur:Integer
  -Nom:String
  -Prénom:String
  -AdressMail:String
  -ModérerMessages()
  -PosterMessage()
  -CacherMessage()
  -AjouterMembre()
  -PromouvoirMembre()
  -FermerRéseauSocial()
  
}

class Message{
  -messageId: Interger
  -content: String
  -Status:EtatMessage
  -authorID:Integer
  -Publier()
  -Cacher()
  -ObtenierStatus()
}

enum ÉtatCompte <<enum>> {
  ACTIF
  DÉSACTIVÉ
  BLOQUÉ
}

enum EtatMembre <<enum>>{
  EnAttente
  Publié
  Rejeté
}

'Associations, etc.'

Administrateur--|> Modérateur
Administrateur-- Utilisateur
Membre --|> Utilisateur 
Modérateur --|> Membre
Modérateur--Membre
Modérateur--MiniSocs
Membre-- Message
Modérateur--Message
Modérateur--MiniSocs
MiniSocs*--"*" Message


'Au besoin, aides pour le positionnement'

@enduml
