@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticiantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants'
actor "__me:Membre__" as me
participant "__:MiniSocs__" as sys
actor "__:Moderateur__" as mo
participant "__r:réseauSocial__" as r
'Interaction principale'
activate me
me -> sys: posterMessage(content)
activate sys

alt content!=vide && estActif(me)
    create "__:Message__" as mes
    sys -> mes++: mes = createMessage(content,me,r)
    return
alt estModerateur(me)
    sys -> r ++: ajouterMessage(mes)
    return
    sys --> me: notifyMessagePosted
else 
    sys --> me: notifymessagePending
    sys -> mo : demandeModération(mes)
    alt message approuvé
    mo -> sys: approuver(mes)
    sys -> r ++: ajouterMessage(mes)
    return
    sys --> me: notifyMessagePosted
    else 
    mo -> sys: refuser(mes)
    sys-->me : notifyMessageRejected
    end
    end
    end
@enduml
