@startuml

'Configuration charte graphique'
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

actor "__:utilisateur__" as m
participant "__:MiniSocs__" as Mini
participant "__r:RéseauSocial__" as RS
participant "__m:Member__" as mod
participant "__u:Utilisateur__" as u
m -> Mini ++: ajouterMembre(pseudonymeModerateur, nomReseauSocial,pseudonymeUtilisateur,pseudonymeMembre)
Mini -> Mini ++: r = chercherReseauSocial(nomReseauSocial): ReseauSocial
return
Mini -> Mini ++: m = chercherMembre(pseudonymeModerateur): Membre
return
Mini -> Mini ++ : u = chercherUtilisateur(pseudonymeUtilisateur) : Utilisateur
return
Mini -> Mini ++ : nm = chercherMembre(pseudonymeMembre) : Membre
return
opt r!=null && m!= null && u!=null && nm==null
    Mini -> mod ++ : test = getEstModerateur(m):Boolean
    return
    Mini -> u ++ : etat = getEtat()
    return
    Mini -> RS ++ : ms = listerModerateur()
    return
    opt test==True  && m in ms && etat==ACTIF
       	   create "__Membre__" as mem
       	   Mini -> mem ++: creerMembre(u,pseudonymeMembre,False,r)
	   return
    end
end
return
@enduml

