@startuml

'Diagramme de cas d'utilisation (PlantUML)'

'Configuration charte graphique'
skinparam usecase {
BackgroundColor White
BorderColor Black
ArrowColor Black
ActorBackgroundColor<< Human >> Gold
}

left to right direction

'Déclaration des acteurs :'
actor Administrateur
actor Utilisateur
Utilisateur <|-- Administrateur
actor Membre
actor Modérateur
Utilisateur <|-- Membre
Membre <|-- Modérateur


'Déclaration des cas d'utilisation dans le système'
rectangle "MiniSocs" {
:Administrateur: -- (Ajouter un utilisateur)
:Administrateur: -- (Lister les utilisateur)
:Administrateur: -- (Bloquer un compte utilisateur)
:Administrateur: --(Debloquer un compte utilisateur)
:Administrateur: --(Retirer utilisateur)
:Utilisateur:    -- (Désactiver son compte)
:Utilisateur: --(Créer réseau social)
:Utilisateur: --(Configurer compte)
:Membre: --(Poster message)
:Membre: --(Cacher message)
:Modérateur: --(Ajouter membre)
:Modérateur: --(Promouvoir membre)
:Modérateur: --(Modérer les messages)
:Utilisateur: --(Activer son compte)

@enduml
