@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticiantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants'
actor "u1:utilisateur" as u1
participant "__m:MiniSocs__" as sys
participant "__r:reseauSocial__" as r
participant "__me:Member__" as m
participant "__u:Utilisateur__" as u
participant "__producteurMessageEnAttente:SubmissionPublisher<Notification>__" as po
participant "__producteurMessagePoste:SubmissionPublisher<Notification>__" as pp 
participant "__u:Utilisateur__" as u

actor "u2:utilisateur" as u2
'Interaction principale'

u1 -> sys++: posterMessage(pseudoUtilisateur,pseudoMembre,contenu,nomReseau)
opt contenu!=null && contenu!=vide && pseudoUtilisateur!= null && pseudoUtilisateur!=vide && pseudoMembre!=null && pseudoMembre!=vide && nomReseau != null && nomReseau!= vide
sys-> sys++: r=chercherReseauSocial(nomReseau) : ReseauSocial
return
sys->sys++:chercherUtilsateurs(pseudoUtilisateur)
return
opt u!=null && r!=null
sys->r++:m=chercherMembre(pseudoMembre)
return
sys-> u ++: etat = getEtatCompte(): EtatCompte
return
sys-> r ++: test = estOuvert(): Boolean
return
sys -> u ++: me = chercherMembre(pseudoMembre):membre
return
opt test && etat==Actif && me==m
create "__mes:Message__" as mes
sys-> mes ++: mes = create(contenu)
return

sys->r ++ : posterMessageDansunReseau(message,pseudo)
r->m ++: Test = estModerateur()
return
alt Test==True
r-> mes : setEtatMessage(VISIBLE)
create "__:Notification__" as no
r-> no ++: no = create(contenu)
return
r -> pp ++: submit(no)
return 
else
create "__:Notification__" as no
r-> no ++: no = create(contenu)
return
r -> po ++: submit(no)
return 
end
return
end
end
end
return
@enduml
