@startuml

'Diagramme de classes (PlantUML)'

'Configuration charte graphique'
hide empty methods
hide circle
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}

'Classes, énumérations, etc.'
class ReseauSocial {
  -id: Interger
  -nom: String
  -description: String
  -estOuvert: Bool
  -ListerModerateur():collection<Membre>
}


class Utilisateur {
  -id: Integer
  -nom: String
  -prenom: String
  -adresseMail: String
  -etatCompte: EtatCompte
  -pseudonyme: String
  -activerCompte()
  -desactiverCompte()
  -creerReseauSocial()
}


class Membre{
  -pseudonyme : String
  -estModerateur : Bool
  -posterMessage()
  -cacherMessage()
  -modererMessage()
  -ajouterMembre()
  -promouvoirMembre()
}

class Message{
  -id: Interger
  -contenu: String
  -statut: EtatMessage
}

class MiniSoc{
}

enum EtatCompte <<enum>> {
  ACTIF
  DÉSACTIVÉ
  BLOQUÉ
}

enum EtatMessage <<enum>>{
  ENATTENTE
  PUBLIE
  REJETE
}

'Associations, etc.'

MiniSoc o-- Utilisateur
MiniSoc o-- ReseauSocial
MiniSoc o-- Membre
Utilisateur <|-- Membre 
Membre "1..*"--"1" ReseauSocial : associer à
Membre "1"-->"..*" Message
ReseauSocial *--"..*" Message


'Au besoin, aides pour le positionnement'

@enduml
