@startuml

'Diagramme de machine à états (PlantUML)

'Configuration charte graphique'

'États et transitions'
state EnCréation : entry: Créer()
state Supprimé : entry: supprimer()

[*] -right-> EnCréation
EnCréation -right-> Brouillon
state c <<choice>>
Brouillon --> c
c --> Visible :[estModérateur]: Publier le message \n/Publier()
c --> EnAttente :[estMembre]: Message en attente d'etre approuvé per le modérateur \n/ Attendre()
state a <<choice>>
EnAttente --> a
a --> Rejeté : Message rejeté par le modérateur\n/Rejeter()
a --> Approuvé 
Rejeté --> Supprimé
Approuvé --> Visible 
Visible --> nonVisible: Message peut etre cacher par son auteur \n/ Cacher()
Visible --> Supprimé : supprimer()
nonVisible --> Supprimé : supprimer()

Supprimé-left->[*]

@enduml
  